server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      -host: unix://var/run/docker.sock
      refresh_internal: 5s
    relabel_configs:
      -source_labels: ['_meta-docker_container_name']
      regex: '/(.*)'
      target)label: 'container'
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log
#          stream: stdout